config/routes.rb
Gma::Application.routes.draw do

  resources :coupons
  resources :anag_socials

  resources :key_words do 
    member do
      get 'manage_key_word_rels'
      get 'change_n_order'
    end
  end

  resources :events

  root :to => "menu#home"

  get "menu/contact"

  get "menu/help"

  match '/signout', :to => 'sessions#destroy'

  resources :sessions, :only => [:new, :create, :destroy]
  
  resources :users do
    collection do
      get :export_filter
      post :do_export_filter
    end
  end

  resources :confs

  resources :localitas do
    collection do
      get :filter
    end
  end

  resources :paeses

  resources :ivas

  resources :causmags

  resources :causales

  resources :agentes

  resources :contos do
    collection do
      get :filter
      get :anagen_exit
    end
  end

  resources :scadenzas do
    collection do
      get :filter
    end
  end

  resources :costos
  resources :spedizs, :only => [:new, :create, :edit, :update, :destroy]  do
    collection do
      get :setind
    end
  end

  resources :articles do
    member do
      get :filter_mov_vend
      get :stp_mov_vend
      get :filter_mov_vend_xls
      get :mov_vend_xls
    end
    collection do
      get :filter
      get :filter_mov_vend_all
      get :stp_mov_vend_all
      get :filter_mov_vend_all_xls
      get :mov_vend_all_xls
      get :set_distrib
    end
  end

  resources :anagens do
    collection do
      get :filter
      get :chg_tipo
      get :change_article
      get :change_event
    end
  end

  resources :anainds do
    collection do
      get :descrizloc
      get :reset_locid
    end
  end

  resources :tesdocs do
    collection do
      get :filter
      get :set_causmags
      get :set_provv
      get :addtesrigdoc_fromxls
      get :genera_xls_articoli
      get :import_by_xml
      post :create_by_xml
      get :form_duplicate
      post :exec_duplicate
    end
    member do
      get :add1row4article
      get :giacyearprec
      get :delrowqta0
      get :stp
      get :dati_ind
      get :stp_ind
      get :ges_datisped
      get :ges_costo
      get :ges_datiscad
      post :addrow_fromxls
      get :upload_xls
    end
  end

  resources :rigdocs do
    collection do
      get :art_cod_exit
      get :art_des_exit
      get :art_sconto_exit
    end
    member do
      get :up
      get :down
    end
  end

	post 'authenticate',  to: 'authentication#authenticate'
  get 'authors',        to: 'anagens#authors'
  get 'teachers',       to: 'anagens#teachers'
  get 'events',         to: 'articles#events'
  get 'categories',     to: 'key_words#categories'
  get 'products',       to: 'articles#products'
  get 'announcements',  to: 'articles#announcements'
  get 'promotions',     to: 'articles#promotions'
  get 'bestsellers',    to: 'articles#bestsellers'
  get 'products',       to: 'articles#products'
  get 'products_query', to: 'articles#products_query'
  get 'anagens_query',  to: 'anagens#anagens_query'
  get 'users_query',    to: 'users#users_query'
  post 'users_query',   to: 'users#users_query'
  get 'get_localitas',  to: 'localitas#localitas_query'
  get 'push_order',     to: 'tesdocs#create_by_json'

  get "api/eshop/v1/get_events",        to: "events#filter_events_ajax"
  get "api/eshop/v1/activate_discount", to: "coupons#activate_discount"











end

app/controllers/articles_controller.rb
require "prawn"
require "prawn/measurement_extensions"

class ArticlesController < ApplicationController

  before_filter :authenticate_request, if: :json_request?
  before_filter :authenticate
  before_filter :force_fieldcase, :only => [:create, :update]

  def set_distrib
    @fl_dis = params[:anarif]=='S'
    @contos = Conto.find_distributori(current_user.azienda, current_annoese)
    respond_to do |format|
      format.js
    end
  end

  def filter_mov_vend
    @tp = params[:tp]
    @article = Article.find(params[:id]) unless params[:id].nil?
    @contos = Conto.find_distributori(current_user.azienda, current_annoese)
    if @contos.empty?
      flash.now[:alert] = "Nessun conto cliente presente"
      render :action => "show"
    end
    if @tp == "M"
      @title = "Stampa Movimenti di magazzino"
      @causmags = Causmag.azienda(current_user.azienda).all(:order=>:descriz)
    else
      @title = "Stampa Vendite per titolo"
      @causmags = Causmag.azienda(current_user.azienda).all(:conditions=>{:contabile=>'S'}, :order=>:descriz)
    end
    @all = false
    @fl_dis = true
  end

  def filter_mov_vend_xls
    @tp = params[:tp]
    @article = Article.find(params[:id]) unless params[:id].nil?
    @contos = Conto.find_distributori(current_user.azienda, current_annoese)
    if @contos.empty?
      flash.now[:alert] = "Nessun conto cliente presente"
      render :action => "show"
    end
    if @tp == "M"
      @title = "Export (XLS) Movimenti di magazzino"
      causmags = Causmag.azienda(current_user.azienda).all(:order=>:descriz)
    else
      @title = "Export (XLS) Vendite per titolo"
      @causmags = Causmag.azienda(current_user.azienda).all(:conditions=>{:contabile=>'S'}, :order=>:descriz)
    end
    @all = false
    @fl_dis = true
  end

  def filter_mov_vend_all
    @tp = params[:tp]
    @contos = Conto.find_distributori(current_user.azienda, current_annoese)
    if @contos.empty?
      flash.now[:alert] = "Nessun conto cliente presente"
      render :action => "index"
    end
    if @tp == "M"
      @title = "Stampa Movimenti di magazzino"
      @causmags = Causmag.azienda(current_user.azienda).all(:order=>:descriz)
    else
      @title = "Stampa Vendite per titolo"
      @causmags = Causmag.azienda(current_user.azienda).all(:conditions=>{:contabile=>'S'}, :order=>:descriz)
    end
    @all = true
    @fl_dis = true
  end

  def filter_mov_vend_all_xls
    @tp = params[:tp]
    @contos = Conto.find_distributori(current_user.azienda, current_annoese)
    if @contos.empty?
      flash.now[:alert] = "Nessun conto cliente presente"
      render :action => "index"
    end
    if @tp == "M"
      @title = "Export (XLS) Movimenti di magazzino"
      @causmags = Causmag.azienda(current_user.azienda).all(:order=>:descriz)
    else
      @title = "Export (XLS) Vendite per titolo"
      @causmags = Causmag.azienda(current_user.azienda).all(:conditions=>{:contabile=>'S'}, :order=>:descriz)
    end
    @all = true
    @fl_dis = true
  end

  def stp_mov_vend
    @tp = params[:tp]
    @id = params[:id]||""
    @idanagen = params[:idconto].to_i>0 ? Conto.find(params[:idconto]).anagen.id : ""
    @nrmag = params[:nrmag]||""
    @anarif = params[:anarif]||""
    @grpmag = params[:grpmag]||""
    @dtini = params[:dtini].to_date if params[:dtini]
    @dtfin = params[:dtfin].to_date if params[:dtfin]
    @idcausmag = params[:causmagfilter]
    @annoese = current_annoese
    @artmov = Tesdoc.art_mov_vend(@id, @idanagen, @nrmag, @anarif, current_user.azienda,
                                  @tp, @annoese, @dtini, @dtfin, @idcausmag)
    @tp == "M" ? @title = "Stampa Movimenti di magazzino" : @title = "Stampa Vendite per titolo"
    if @artmov.count == 0
      render 'mov_vend_notfound'
    else
      render 'stp_mov_vend.pdf'
    end
  end

  def stp_mov_vend_all
    @tp = params[:tp]
    @idanagen = params[:idconto].to_i>0 ? Conto.find(params[:idconto]).anagen.id : ""
    @nrmag = params[:nrmag]||""
    @anarif = params[:anarif]||""
    @grpmag = params[:grpmag]||""
    @dtini = params[:dtini].to_date if params[:dtini]
    @dtfin = params[:dtfin].to_date if params[:dtfin]
    @idcausmag = params[:causmagfilter]
    @annoese = current_annoese
    @artmov = Tesdoc.art_mov_vend("all", @idanagen, @nrmag, @anarif, current_user.azienda,
                                         @tp, @annoese, @dtini, @dtfin, @idcausmag)
    @tp == "M" ? @title = "Stampa Movimenti di magazzino" : @title = "Stampa Vendite per titolo"
    if @artmov.count == 0
      render 'mov_vend_notfound'
    else
      render 'stp_mov_vend.pdf'
    end
  end

  def mov_vend_xls
    @tp = params[:tp]
    @id = params[:id]||""
    @idanagen = params[:idconto].to_i>0 ? Conto.find(params[:idconto]).anagen.id : ""
    @nrmag = params[:nrmag]||""
    @anarif = params[:anarif]||""
    @grpmag = params[:grpmag]||""
    @dtini = params[:dtini].to_date if params[:dtini]
    @dtfin = params[:dtfin].to_date if params[:dtfin]
    @idcausmag = params[:causmagfilter]
    @artmov = Tesdoc.art_mov_vend(@id, @idanagen, @nrmag, @anarif, current_user.azienda,
                                  @tp, current_annoese, @dtini, @dtfin, @idcausmag)
    @tp == "M" ? @title = "Export (XLS) Movimenti di magazzino" : @title = "Export (XLS) Vendite per titolo"
    if @artmov.count == 0
      render 'mov_vend_notfound'
    else
      data=Article.exp_movart_xls(@tp, @artmov, @idanagen, @nrmag, @anarif, current_user.azienda,
                                  @grpmag, current_annoese, @dtini, @dtfin, @idcausmag)
      send_data(data, {
        :disposition => 'attachment',
        :encoding => 'utf8',
        :stream => false,
        :type => 'application/excel',
        :filename => './mov_art.xls'})
    end
  end

  def mov_vend_all_xls
    @tp = params[:tp]
    @idanagen = params[:idconto].to_i>0 ? Conto.find(params[:idconto]).anagen.id : ""
    @nrmag = params[:nrmag]||""
    @anarif = params[:anarif]||""
    @grpmag = params[:grpmag]||""
    @dtini = params[:dtini].to_date if params[:dtini]
    @dtfin = params[:dtfin].to_date if params[:dtfin]
    @idcausmag = params[:causmagfilter]||""
    @artmov = Tesdoc.art_mov_vend("all", @idanagen, @nrmag, @anarif, current_user.azienda,
                                         @tp, current_annoese, @dtini, @dtfin, @idcausmag)
    @tp == "M" ? @title = "Export (XLS) Movimenti di magazzino" : @title = "Export (XLS) Vendite per titolo"
    if @artmov.count == 0
      render 'mov_vend_notfound'
    else
      data=Article.exp_movart_xls(@tp, @artmov, @idanagen, @nrmag, @anarif, current_user.azienda,
                                  @grpmag, current_annoese, @dtini, @dtfin, @idcausmag)
      send_data(data, {
        :disposition => 'attachment',
        :encoding => 'utf8',
        :stream => false,
        :type => 'application/excel',
        :filename => './mov_art.xls'})
    end
  end

  def filter
    @title = "Elenco Articoli"
    @tpfilter  = params[:tpfilter]
    @desfilter = params[:desfilter].strip
    @articles, nrrecord = Article.filter(current_user.azienda, @tpfilter, @desfilter, params[:page])
    flash_cnt(nrrecord) if params[:page].nil?
    store_location
    render "index"
  end

  def index
    @title = "Elenco Articoli"
    store_location
  end

  def show
    @title = "Mostra Articolo"
    @article = Article.find(params[:id])
    @key_words_addable = KeyWord.sort_by_din(KeyWordArticle.all)

    @art_author = @article.anagen_articles.by_author
    @art_print  = @article.anagen_articles.by_printer
    @art_suppl  = @article.anagen_articles.by_supplier
    @authors_addable   = Anagen.authors
    @printers_addable  = Anagen.printers
    @suppliers_addable = Anagen.suppliers

    @events = @article.events.order(:dt_event)

    respond_to do |format|
      format.html # renders .html.erb
      #format.json { render :json => { st: true, v: @anagen.to_json } }
      format.json { render json: map_json_data(@article) }
    end
  end

  def new
    @title = "Nuovo Articolo"
    @article = Article.new
    @article.azienda = current_user.azienda
    @article.costo = 0.0
  end

  def edit
    @title = "Modifica Articolo"
    @article = Article.find(params[:id])
  end

  def create
    @article = Article.new(params[:article])
    if @article.save
      flash[:success] = 'Articolo inserito con successo.'
      redirect_to @article
    else
      @title = "Nuovo Articolo"
      render :action => "new"
    end
  end

  def update
    @article = Article.find(params[:id])
    if @article.update_attributes(params[:article])
      flash[:success] = 'Articolo aggiornato con successo.'
      redirect_to @article
    else
      @title = "Modifica Articolo"
      render :action => "edit"
    end
  end

  def destroy
    @article = Article.find(params[:id])
    begin
      @article.destroy
      flash[:success] = "Cancellazione Eseguita"
    rescue
      flash[:alert] = $!.message
    end
    redirect_back_or @article
  end

  def events
    ds = Article.corsi
    render json: map_json_array(ds)
  end

  def announcements
    n = params[:limit] ? params[:limit].to_i : 0
    ds = Article.announcements(n)
    render json: map_json_array(ds) 
  end
  
  def promotions
    n = params[:limit] ? params[:limit].to_i : 0
    ds = Article.promotions(n)
    render json: map_json_array(ds) 
  end
  
  def bestsellers
    n = params[:limit] ? params[:limit].to_i : 0
    ds = Article.bestsellers(n)
    render json: map_json_array(ds) 
  end
  
  def products
    n = params[:limit] ? params[:limit].to_i : 0
    ds = Article.products(n)
    render json: map_json_array(ds) 
  end
  
  def products_query
    Rails.logger.info "------- params: #{params}"

app/views/articles/_anagens.html.erb
<div class="six columns">
  <table>
    <thead>
      <tr>
        <th width="90%">Titolo</th>
        <th width="5%"></th>
        <th width="5%"></th>
      </tr>
    </thead>
    <tbody>
      <% anagen_articles.each do |an_art| %>
        <% ana = an_art.anagen %>
        <% if ana %>
          <tr>
            <td><%= ana.denomin %></td>
            <td><%= link_to '', ana, :class => "button radius tiny view foundicon-page", :title => "Visualizza" %></td>
            <td><%= link_to '', change_article_anagens_path(id: ana.id, article_id: @article.id, mode: 2), :confirm => 'Confermi?', :class => "button radius tiny alert foundicon-trash", :title => "Cancella" %></td>
          </tr>
        <% end %>
      <% end %>
    </tbody>
  </table>
</div>

<div class="six columns">
  <%= form_tag( change_article_anagens_path(), method: :get ) do %>
    <%= hidden_field_tag :article_id, @article.id %>
    <%= hidden_field_tag :mode, 1 %>
    <%= select_tag "id", options_from_collection_for_select(addables, "id", "denomin")%>
    <div class="action">
      <%= submit_tag "Collega" %>
    </div>
  <% end %> 
</div>

app/views/articles/_buttons.html.erb
<div class="button-bar">
  <ul class="button-group">
    <li>
      <%= link_to 'INDIETRO',  resque_location(articles_path), :class => "button radius small back foundicon-left-arrow" %>
    </li>
    <li>
      <%= link_to 'MODIFICA', edit_article_path(@article), :class => "button radius small modify foundicon-edit" %>
    </li>
    <li>
      <%= link_to 'ELIMINA', @article, :confirm => 'Confermi eliminazione?',
                                       :method => :delete, :class => "button radius small alert foundicon-trash" %>
    </li>
  </ul>
  <%= render :partial => 'btn_stp' %>
</div>

app/views/articles/_event_states.html.erb
<div class="row">
  <div class="twelve columns">
    <%= link_to 'Aggiungi', new_event_path(article_id: params[:id]), :class => "button radius small back" %>

    <table>
      <thead>
        <tr>
          <th width="5%">Data 1</th>
          <th width="10%">Orari</th>
          <th width="15%">Sede</th>
          <th width="18%">Insegnanti</th>
          <th width="18%">Organizzatori</th>
          <th width="10%">Abbigliamento</th>
          <th width="4%">Stato</th>
          <th width="16%"></th>
        </tr>
      </thead>
      <tbody>
        <% events.each do |event| %>
          <tr>
            <td> <%= to_date(event.dt_event) %> </td>
            <td> <%= event.timetable %> </td>
            <td> <%= event.dsite_anagen %> </td>
            <td> <%= event.dteachers %> </td>
            <td> <%= event.dorganizers %> </td>
            <td> <%= event.dressing %> </td>
            <td> <%= event.dstate %> </td>
            <td> <%= render :partial => 'shared/btn_vmc', :locals => {:v_edit => edit_event_path(event), :line => event} %> </td>
          </tr>
        <% end %>
      </tbody>
    </table>

  </div>
</div>

app/views/articles/_event_states_course.html.erb
<div class="row">
  <div class="twelve columns">
    <%= link_to 'Aggiungi', new_event_path(article_id: params[:id]), :class => "button radius small back" %>

    <table>
      <thead>
        <tr>
          <th width="5%">Data</th>
          <th width="10%">Orari</th>
          <th width="15%">Sede</th>
          <th width="18%">Insegnanti</th>
          <th width="18%">Organizzatori</th>
          <th width="10%">Abbigliamento</th>
          <th width="4%">Stato</th>
          <th width="16%"></th>
        </tr>
      </thead>
      <tbody>
        <% events.each do |event| %>
          <tr>
            <td> <%= to_date(event.dt_event) %> </td>
            <td> <%= event.timetable %> </td>
            <td> <%= event.dsite_anagen %> </td>
            <td> <%= event.dteachers %> </td>
            <td> <%= event.dorganizers %> </td>
            <td> <%= event.dressing %> </td>
            <td> <%= event.dstate %> </td>
            <td> <%= render :partial => 'shared/btn_vmc', :locals => {:v_edit => edit_event_path(event), :line => event} %> </td>
          </tr>
        <% end %>
      </tbody>
    </table>

  </div>
</div>

app/views/articles/_event_states_magazine.html.erb
<div class="row">
  <div class="twelve columns">
    <%= link_to 'Aggiungi', new_event_path(article_id: params[:id]), :class => "button radius small back" %>

    <table>
      <thead>
        <tr>
          <th width="20%">Data</th>
          <th width="10%">Numero</th>
          <th width="10%">Anno</th>
          <th width="30%">Tiratura</th>
          <th width="30%"></th>
        </tr>
      </thead>
      <tbody>
        <% events.each do |event| %>
          <tr>
            <td> <%= to_date(event.dt_event) %> </td>
            <td> <%= event.nr_item %> </td>
            <td> <%= event.yr_item %> </td>
            <td> <%= event.quantity %> </td>
            <td> <%= render :partial => 'shared/btn_vmc', :locals => {:v_edit => edit_event_path(event), :line => event} %> </td>
          </tr>
        <% end %>
      </tbody>
    </table>

  </div>
</div>

app/views/articles/_filter.html.erb
<fieldset>
  <legend> Ricerca articoli </legend>
  <%= form_tag(:filter_articles, :method => :get) do %>
    <div class="three columns">
      <%= select_tag("tpfilter",
                     options_for_select([["Descrizione", "DE"], ["Codice", "CO"]], @tpfilter)) %>
    </div>
    <div class="five columns">
      <%= text_field_tag "desfilter", @desfilter %>
    </div>
    <div class="four columns">
      <i class="foundicon-search">
        <%= submit_tag 'RICERCA', :class => "button radius small search foundicon-search", :title => "Esegui Ricerca" %>
      </i>
    </div>
  <% end %>
</fieldset>

app/views/articles/_info.html.erb
<div class="row">
  <div class="two columns">
    <%= label @article, "Codice:", :class => "right" %>
  </div>
  <div class="four columns left">
    <%= @article.codice %>
  </div>
  <div class="two columns">
    <%= label @article, "Prezzo di acquisto:", :class => "right" %>
  </div>
  <div class="four columns left">
    <%= @article.costo %> 
  </div>
</div>

<div class="row">
  <div class="two columns">
    <%= label @article, "Categoria:", :class => "right" %>
  </div>
  <div class="four columns left">
    <%= Article::CATEG[@article.categ] %>
  </div>
  <div class="two columns">
    <%= label @article, "Prezzo di vendita:", :class => "right" %>
  </div>
  <div class="four columns left">
    <%= @article.prezzo %> 
  </div>
</div>

<div class="row">
  <div class="two columns">
    <%= label @article, "Peso (gr):", :class => "right" %>
  </div>
  <div class="four columns left">
    <%= @article.weigth %>
  </div>
  <div class="two columns">
    <%= label @article, "Pezzi x confezione:", :class => "right" %>
  </div>
  <div class="four columns left">
    <%= @article.ppc %>
  </div>
</div>

<div class="row">
  <div class="two columns">
    <%= label @article, "Larghezza (mm):", :class => "right" %>
  </div>
  <div class="four columns left">
    <%= @article.width %>
  </div>
  <div class="two columns">
    <%= label @article, "Pezzi x scatola:", :class => "right" %>
  </div>
  <div class="four columns left">
    <%= @article.ppb %>
  </div>
</div>

<div class="row">
  <div class="two columns">
    <%= label @article, "Altezza (mm):", :class => "right" %>
  </div>
  <div class="four columns left">
    <%= @article.height %>
  </div>
  <div class="two columns">
    <%= label @article, "Data pubb:", :class => "right" %>
  </div>
  <div class="four columns left">
    <%= to_mydate(@article.dtpub) %>
  </div>
</div>

<div class="row">
  <div class="two columns">
    <%= label @article, "Stato:", :class => "right" %>
  </div>
  <div class="four columns left">
    <%= @article.dstate %>
  </div>

  <div class="two columns">
    <%= label @article, "Sconto:", :class => "right" %>
  </div>
  <div class="four columns left">
    <%= @article.discount %> %
  </div>
</div>

<div class="row">
  <div class="two columns">
    <%= label @article, "Numero pagine:", :class => "right" %>
  </div>
  <div class="four columns left">
    <%= @article.pagine %>
  </div>
  <div class="two columns">
    <%= label @article, "Prezzo scontato:", :class => "right" %>
  </div>
  <div class="four columns left">
    <%= @article.final_price %> 
  </div>
</div>

<div class="row">
  <div class="two columns">
    <%= label @article, "Rilegatura:", :class => "right" %>
  </div>
  <div class="four columns left">
    <%= @article.drilegatura %>
  </div>
  <div class="two columns">
    <%= label @article, "Link pres. YouTube:", :class => "right" %>
  </div>
  <div class="four columns left">
    <%= link_to @article.youtube_presentation, @article.youtube_presentation, target: "_blank" %>
  </div>
</div>

<div class="row">
  <div class="two columns">
    <%= label @article, "Traduttore:", :class => "right" %>
  </div>
  <div class="four columns left">
    <%= @article.translator %>
  </div>
  <div class="two columns">
    <%= label @article, "A cura di:", :class => "right" %>
  </div>
  <div class="four columns left">
    <%= @article.collaborator %>
  </div>
</div>

<div class="row">
  <div class="two columns">
    <%= label @article, "Collana:", :class => "right" %>
  </div>
  <div class="four columns left">
    <%= @article.series %>
  </div>
  <div class="two columns">
    <%= label @article, "Direttore di collana:", :class => "right" %>
  </div>
  <div class="four columns left">
    <%= @article.director_series %>
  </div>
</div>

<div class="row">
  <div class="two columns">
    <%= label @article, "Descrizione:", :class => "right" %>
  </div>
  <div class="ten columns left">
    <%= @article.descriz %>
  </div>
</div>
<div class="row">
  <div class="two columns">
    <%= label @article, "Sottotitolo:", :class => "right" %>
  </div>
  <div class="ten columns left">
    <%= @article.subtitle %>
  </div>
</div>

<div class="row">
  <div class="two columns">
    <%= label @article, "Sinossi:", :class => "right" %>
  </div>
  <div class="ten columns left">
    <%= @article.sinossi %>
  </div>
</div>
<div class="row">
  <div class="two columns">
    <%= label @article, "Abstract:", :class => "right" %>
  </div>
  <div class="ten columns left">
    <%= @article.abstract %>
  </div>
</div>
<div class="row">
  <div class="two columns">
    <%= label @article, "Commento:", :class => "right" %>
  </div>
  <div class="ten columns left">
    <%= @article.quote %>
  </div>
</div>
<div class="row">
  <div class="two columns">
    <%= label @article, "Link Issuee:", :class => "right" %>
  </div>
  <div class="ten columns left">
    <%= @article.issuee_link %>
  </div>
</div>

<br>
<%= render "rel_datas" %>

app/views/articles/cvenddistnotfound.html.erb
<h1>Vendite per distributore</h1>
<br/>
<br/>
<br/>
<br/>
<br/>

<h2>Nessun distributore trovato</h2>

<%= link_to 'Indietro', :back %>

app/views/articles/filter_mov_vend.html.erb
<%= render :partial => 'shared/page_title', :locals => {:record => nil} %>
<%= render :partial => 'stp_filter', :locals => {:url => :stp_mov_vend_article, 
                                                 :url_back => @article} %>

app/views/articles/filter_mov_vend_all.html.erb
<%= render :partial => 'shared/page_title', :locals => {:record => nil} %>
<%= render :partial => 'stp_filter', :locals => {:url => :stp_mov_vend_all_articles, 
                                                 :sub_label => 'STAMPA',
                                                 :url_back => articles_path} %>

app/views/articles/filter_mov_vend_all_xls.html.erb
<%= render :partial => 'shared/page_title', :locals => {:record => nil} %>
<%= render :partial => 'stp_filter', :locals => {:url => :mov_vend_all_xls_articles, 
                                                 :sub_label => 'EXPORT(XLS)',
                                                 :url_back => articles_path} %>

app/views/articles/index.html.erb
<%= render :partial => 'shared/page_title', :locals => {:record => nil} %>
<div class="button-bar">
  <ul class="button-group">
    <li>
      <%= link_to 'NUOVO', new_article_path, :class => "button radius small new foundicon-add-doc" %>
    </li>
  </ul>
  <%= render :partial => 'btn_stp' %>
</div>
<%= render :partial => 'filter' %>
<% unless @articles.nil?||@articles.empty? %>
  <table>
    <thead>
      <tr>
        <th width="12%">Codice</th>
        <th width="6%">Categ.</th>
        <th width="44%">Descrizione</th>
        <th class="currency" width="10%">Prezzo Vendita</th>
        <th class="currency" width="10%">Prezzo Acquisto</th>
        <th width="18%"></th>
      </tr>
    </thead>
    <tbody>
        <%= render :partial => 'line', :collection => @articles %>
    </tbody>
  </table>
  <%= will_paginate @articles %>
<% end %>

app/views/articles/new.html.erb
<%= render :partial => 'shared/page_title', :locals => {:record => @article} %>
<%= render 'form' %>