config/routes.rb
Gma::Application.routes.draw do

  resources :coupons
  resources :anag_socials

  resources :key_words do 
    member do
      get 'manage_key_word_rels'
      get 'change_n_order'
    end
  end

  resources :events

  root :to => "menu#home"

  get "menu/contact"

  get "menu/help"

  match '/signout', :to => 'sessions#destroy'

  resources :sessions, :only => [:new, :create, :destroy]
  
  resources :users do
    collection do
      get :export_filter
      post :do_export_filter
    end
  end

  resources :confs

  resources :localitas do
    collection do
      get :filter
    end
  end

  resources :paeses

  resources :ivas

  resources :causmags

  resources :causales

  resources :agentes

  resources :contos do
    collection do
      get :filter
      get :anagen_exit
    end
  end

  resources :scadenzas do
    collection do
      get :filter
    end
  end

  resources :costos
  resources :spedizs, :only => [:new, :create, :edit, :update, :destroy]  do
    collection do
      get :setind
    end
  end

  resources :articles do
    member do
      get :filter_mov_vend
      get :stp_mov_vend
      get :filter_mov_vend_xls
      get :mov_vend_xls
    end
    collection do
      get :filter
      get :filter_mov_vend_all
      get :stp_mov_vend_all
      get :filter_mov_vend_all_xls
      get :mov_vend_all_xls
      get :set_distrib
    end
  end

  resources :anagens do
    collection do
      get :filter
      get :chg_tipo
      get :change_article
      get :change_event
    end
  end

  resources :anainds do
    collection do
      get :descrizloc
      get :reset_locid
    end
  end

  resources :tesdocs do
    collection do
      get :filter
      get :set_causmags
      get :set_provv
      get :addtesrigdoc_fromxls
      get :genera_xls_articoli
      get :import_by_xml
      post :create_by_xml
      get :form_duplicate
      post :exec_duplicate
    end
    member do
      get :add1row4article
      get :giacyearprec
      get :delrowqta0
      get :stp
      get :dati_ind
      get :stp_ind
      get :ges_datisped
      get :ges_costo
      get :ges_datiscad
      post :addrow_fromxls
      get :upload_xls
    end
  end

  resources :rigdocs do
    collection do
      get :art_cod_exit
      get :art_des_exit
      get :art_sconto_exit
    end
    member do
      get :up
      get :down
    end
  end

	post 'authenticate',  to: 'authentication#authenticate'
  get 'authors',        to: 'anagens#authors'
  get 'teachers',       to: 'anagens#teachers'
  get 'events',         to: 'articles#events'
  get 'categories',     to: 'key_words#categories'
  get 'products',       to: 'articles#products'
  get 'announcements',  to: 'articles#announcements'
  get 'promotions',     to: 'articles#promotions'
  get 'bestsellers',    to: 'articles#bestsellers'
  get 'products',       to: 'articles#products'
  get 'products_query', to: 'articles#products_query'
  get 'anagens_query',  to: 'anagens#anagens_query'
  get 'users_query',    to: 'users#users_query'
  post 'users_query',   to: 'users#users_query'
  get 'get_localitas',  to: 'localitas#localitas_query'
  get 'push_order',     to: 'tesdocs#create_by_json'

  get "api/eshop/v1/get_events",        to: "events#filter_events_ajax"
  get "api/eshop/v1/activate_discount", to: "coupons#activate_discount"











end

app/models/key_word.rb
class KeyWord < ActiveRecord::Base
  # attr_accessible :title, :body
  attr_accessible :desc, :parent_id, :keyword_type, :type, :n_order, :state

  belongs_to :parent, class_name: "KeyWord" , foreign_key: "parent_id"
  has_many :childs, class_name: "KeyWord" , foreign_key: "parent_id", dependent: :destroy
  has_many :key_word_rels, dependent: :destroy

  before_create :assign_type
  after_create :set_n_order

  default_scope order("n_order ASC")
  
  scope :not_hidden, -> { where(state: 1) }

  STATES = [ ["Nascosto",0], ["Visibile",1] ]

  def get_dinasty
    if self.parent
      msg = "/ %s "%[self.desc]
      msg = self.parent.get_dinasty+msg
      msg
    else
      ""
    end
  end

  def connect_item(ot_cls, ot_id)
    other    = ot_cls.find(ot_id)

    self.key_word_rels << KeyWordRel.create(key_wordable: other)
  end

  def remove_item(kwr_id)
    tmp = self.key_word_rels.find(kwr_id)
    tmp.destroy
  end

  def leaf?
    self.childs.count == 0
  end

  def self.sort_by_din(ds)
    ds.sort_by { |x| x.get_dinasty }
  end

  def set_n_order
    x = self.parent && self.parent.childs.last
    x = x && x.n_order + 1 || 1
    self.n_order = x
    self.save
  end

  # 1 -> UP
  # 2 -> DOWN
  def change_n_order(mode)
    return false unless self.parent

    if mode == 1
      if self.n_order != 1
        kw = self.parent.childs.where(n_order: self.n_order-1).first
        if kw
          kw.n_order += 1
          self.n_order -= 1
          kw.save
          self.save
        end
      end

    elsif mode == 2
    kw = self.parent.childs.where(n_order: self.n_order+1).last
    puts "---- kw: #{kw.n_order} vs self: #{self.n_order}"
    if kw && self.n_order < kw.n_order
      kw.n_order -= 1
      self.n_order += 1
      kw.save
      self.save
      end
    end
  end

  def get_childs
    ris = []
    self.childs.each do |c|
      if c.childs.count > 0
        c.childs.each { |x| ris << x.get_childs }
      else
        ris << c
      end
    end
    ris
  end

  def d_state
    tmp = STATES.select { |a,b| b == self.state }
    tmp.size > 0 ? tmp[0][0] : ''
  end

  private
    def assign_type
      if !self.type && self.parent
        self.type = self.parent.type
      end
    end

end

app/controllers/key_words_controller.rb
class KeyWordsController < ApplicationController
  # GET /key_words
  # GET /key_words.json
  def index
    @key_words = KeyWord.where(parent_id: nil)
    @title = "Key Words"

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @key_words }
    end
  end

  # GET /key_words/1
  # GET /key_words/1.json
  def show
    @title = "Key Word"
    @key_word = KeyWord.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: KeyWordArticle.map_json_data(@key_word) }
    end
  end

  # GET /key_words/new
  # GET /key_words/new.json
  def new
    @title = "Nuova Key Word"
    @key_word = KeyWord.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @key_word }
    end
  end

  # GET /key_words/1/edit
  def edit
    @title = "Modifica Key Word"
    @key_word = KeyWord.find(params[:id])
  end

  # POST /key_words
  # POST /key_words.json
  def create
    @key_word = KeyWord.new(params[:key_word])

    respond_to do |format|
      if @key_word.save
        format.html { redirect_to key_word_path(@key_word), notice: 'Key word was successfully created.' }
        format.json { render json: @key_word, status: :created, location: @key_word }
      else
        format.html { render action: "new" }
        format.json { render json: @key_word.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /key_words/1
  # PUT /key_words/1.json
  def update
    @key_word = KeyWord.find(params[:id])

    respond_to do |format|
      if @key_word.update_attributes(params[:key_word])
        format.html { redirect_to key_word_path(@key_word), notice: 'Key word was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @key_word.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /key_words/1
  # DELETE /key_words/1.json
  def destroy
    @key_word = KeyWord.find(params[:id])
    @key_word.destroy

    respond_to do |format|
      format.html { redirect_to key_words_url }
      format.json { head :no_content }
    end
  end

  def manage_key_word_rels
    @key_word = KeyWord.find(params[:id])
    notice = "OK"

    case params[:mode]
    when "0" #inserimento
      ot_id = params[:ot_id] && params[:ot_id].to_i
      ot_cls = params[:ot_cls] 
      if ot_id
        @key_word.connect_item(ot_cls.constantize, ot_id)
        notice = "KeyWord aggiunta."
      else
        notice = "Errore. KeyWord non valida."
      end

    when "1" #eliminazione
      kwr_id = params[:kwr_id] && params[:kwr_id].to_i
      if kwr_id
        @key_word.remove_item(kwr_id)
        notice = "KeyWord eliminata."
      else
        notice = "Errore. KeyWord non valida."
      end

    end

    redirect_to :back, notice: notice
  end

  def categories
    kw = KeyWordArticle.ecomm_root
    render json: kw
  end

  def change_n_order
    @key_word = KeyWord.find(params[:id])
    mode = params[:mode] && params[:mode].to_i
    @key_word.change_n_order(mode)
    redirect_to :back
  end
end

app/helpers/key_words_helper.rb
module KeyWordsHelper
end

app/views/key_words/_childs.html.erb
<div class="twelve columns">
  <table>
    <thead>
      <tr>
        <th width="30%">Descrizione</th>
        <th width="25%"></th>
        <th width="3%"></th>
      </tr>
    </thead>
    <tbody>
      <%= render partial: 'line', collection: @key_word.childs, as: :item %>
    </tbody>
  </table>
</div>

app/views/key_words/_form.html.erb
<%= form_for(@key_word, as: :key_word, url: { controller: :key_words, action: @key_word.new_record? ? :create : :update}) do |f| %>
    <%= f.hidden_field :parent_id, value: params[:parent_id] if params[:parent_id] %>
    <div class="row">
      <div class="six columns">
        <%= f.label "Descrizione" %>
        <%= f.text_field :desc, value: @key_word.desc %>
      </div>
    </div>

    <div class="row">
      <div class="two columns">
        <%= f.label "Stato" %>
        <%= select(:key_word, :state, (KeyWord::STATES)) %>
      </div>
    </div>


    <div class="twelve columns">
      <%= f.submit 'SALVA', :class => "button radius small success foundicon-checkmark" %>
      <%= link_to 'ANNULLA', key_words_path, :class => "button radius small alert foundicon-remove" %>
    </div>
  </div>
<% end %>

app/views/key_words/_line.html.erb
<tr>
  <td><%= item.desc %></td>
  <td>
    <%= link_to '', key_word_path(item), :class => "button radius tiny detail foundicon-page", :title => "Dettaglio" %>
    <%= link_to 'UP', change_n_order_key_word_path(id: item.id, mode: 1), :class => "button radius tiny detail ", :title => "UP" %>
    <%= link_to 'DW', change_n_order_key_word_path(id: item.id, mode: 2), :class => "button radius tiny detail ", :title => "DW" %>
  </td>
  </td>
</tr>

app/views/key_words/edit.html.erb
<%= render :partial => 'shared/page_title', :locals => {:record => @event} %>
<%= render 'form' %>

app/views/key_words/index.html.erb
<%= render :partial => 'shared/page_title', :locals => {:record => nil} %>

<% unless @key_words.nil?||@key_words.empty? %>
  <table>
    <thead>
      <tr>
        <th width="10%">Descrizione</th>
        <th width="5%"></th>
      </tr>
    </thead>
    <tbody>
        <%= render :partial => 'line', :collection => @key_words, as: :item %>
    </tbody>
  </table>
<% end %>

app/views/key_words/new.html.erb
<%= render :partial => 'shared/page_title', :locals => {:record => @event} %>
<%= render 'form' %>

app/views/key_words/show.html.erb
<%= render :partial => 'shared/page_title', :locals => {:record => nil} %>
<div class="row">
  <div class="twelve columns button-bar">
    <ul class="button-group">
      <li>
        <%= link_to 'INDIETRO', @key_word.parent ? key_word_path(@key_word.parent) : key_words_path, :class => "button radius small cancel foundicon-left-arrow" %>
      </li>
      <li>
        <%= link_to 'MODIFICA', edit_key_word_path(@key_word), :class => "button radius small modify foundicon-edit" %>
      </li>
      <li>
        <%= link_to 'NUOVO SOTTOELEMENTO', new_key_word_path(parent_id: @key_word.id), :class => "button radius small modify foundicon-edit" %>
      </li>
      <!--<li>
        <%= link_to 'ELIMINA', key_word_path(@key_word), :confirm => 'Confermi eliminazione?',
                                        :method => :delete, :class => "button radius small alert foundicon-trash" %>
      </li>-->
    </ul>
  </div>
</div>

<div class="row">
  <div class="two columns">
    <%= label @key_word, "Descrizione:", :class => "right" %>
  </div>
  <div class="two columns left">
    <%= @key_word.desc %>
  </div>
  <div class="two columns">
    <%= label @key_word, "Percorso:", :class => "right" %>
  </div>
  <div class="four columns left">
    <%= @key_word.get_dinasty %>
  </div>
  <div class="two columns left">
    <b><%= @key_word.d_state %></b>
  </div>
</div>

<%= render "childs" %>