config/routes.rb
Gma::Application.routes.draw do

  resources :coupons
  resources :anag_socials

  resources :key_words do 
    member do
      get 'manage_key_word_rels'
      get 'change_n_order'
    end
  end

  resources :events

  root :to => "menu#home"

  get "menu/contact"

  get "menu/help"

  match '/signout', :to => 'sessions#destroy'

  resources :sessions, :only => [:new, :create, :destroy]
  
  resources :users do
    collection do
      get :export_filter
      post :do_export_filter
    end
  end

  resources :confs

  resources :localitas do
    collection do
      get :filter
    end
  end

  resources :paeses

  resources :ivas

  resources :causmags

  resources :causales

  resources :agentes

  resources :contos do
    collection do
      get :filter
      get :anagen_exit
    end
  end

  resources :scadenzas do
    collection do
      get :filter
    end
  end

  resources :costos
  resources :spedizs, :only => [:new, :create, :edit, :update, :destroy]  do
    collection do
      get :setind
    end
  end

  resources :articles do
    member do
      get :filter_mov_vend
      get :stp_mov_vend
      get :filter_mov_vend_xls
      get :mov_vend_xls
    end
    collection do
      get :filter
      get :filter_mov_vend_all
      get :stp_mov_vend_all
      get :filter_mov_vend_all_xls
      get :mov_vend_all_xls
      get :set_distrib
    end
  end

  resources :anagens do
    collection do
      get :filter
      get :chg_tipo
      get :change_article
      get :change_event
    end
  end

  resources :anainds do
    collection do
      get :descrizloc
      get :reset_locid
    end
  end

  resources :tesdocs do
    collection do
      get :filter
      get :set_causmags
      get :set_provv
      get :addtesrigdoc_fromxls
      get :genera_xls_articoli
      get :import_by_xml
      post :create_by_xml
      get :form_duplicate
      post :exec_duplicate
    end
    member do
      get :add1row4article
      get :giacyearprec
      get :delrowqta0
      get :stp
      get :dati_ind
      get :stp_ind
      get :ges_datisped
      get :ges_costo
      get :ges_datiscad
      post :addrow_fromxls
      get :upload_xls
    end
  end

  resources :rigdocs do
    collection do
      get :art_cod_exit
      get :art_des_exit
      get :art_sconto_exit
    end
    member do
      get :up
      get :down
    end
  end

	post 'authenticate',  to: 'authentication#authenticate'
  get 'authors',        to: 'anagens#authors'
  get 'teachers',       to: 'anagens#teachers'
  get 'events',         to: 'articles#events'
  get 'categories',     to: 'key_words#categories'
  get 'products',       to: 'articles#products'
  get 'announcements',  to: 'articles#announcements'
  get 'promotions',     to: 'articles#promotions'
  get 'bestsellers',    to: 'articles#bestsellers'
  get 'products',       to: 'articles#products'
  get 'products_query', to: 'articles#products_query'
  get 'anagens_query',  to: 'anagens#anagens_query'
  get 'users_query',    to: 'users#users_query'
  post 'users_query',   to: 'users#users_query'
  get 'get_localitas',  to: 'localitas#localitas_query'
  get 'push_order',     to: 'tesdocs#create_by_json'

  get "api/eshop/v1/get_events",        to: "events#filter_events_ajax"
  get "api/eshop/v1/activate_discount", to: "coupons#activate_discount"











end

app/views/shared/_btn_vmc.html.erb
<%= link_to '', line, :class => "button radius tiny view foundicon-page", :title => "Visualizza" %>
<%= link_to '', v_edit, :class => "button radius tiny modify foundicon-edit", :title => "Modifica" %>
<%= link_to '', line, :confirm => 'Confermi?',        :method => :delete,
                       :class => "button radius tiny alert foundicon-trash", :title => "Cancella" %>

app/views/shared/_error_messages.html.erb
<% if f.errors.any? %>
  <div class="row">
    <div class="twelve columns end error">
      <div class="alert-box alert" >
        <div id="error_explanation">
            <%= pluralize(f.errors.count, "errore", "errori") %>
            :Salvataggio dati NON riuscito:
          <ul>
            <% f.errors.full_messages.each do |msg| %>
              <li> <%= msg %> </li>
            <% end %>
          </ul>
        </div>
      </div>
    </div>
  </div>
<% end %>

app/views/shared/_key_word_rels.html.erb
<div class="row">
  <div class="six columns">
    <table>
      <thead>
        <tr>
          <th width="90%">Key Word Associate</th>
          <th width="10%"></th>
        </tr>
      </thead>
      <tbody>
        <% orig.key_word_rels.each do |item| %>
          <% if item.key_word %>
            <tr>
              <td><%= item.key_word.get_dinasty %></td>
              <td>
                <%= link_to '', manage_key_word_rels_key_word_path(id: item.key_word.id, mode: 1, kwr_id: item.id), 
                  confirm: 'Confermi?', class: "button radius tiny alert foundicon-trash", title: "Cancella" %>
              </td>
            </tr>
          <% end %>
        <% end %>
        </tbody>
    </table>
  </div>
  <div class="six columns">
    <table>
      <thead>
        <tr>
          <th width="90%">Key Word Associabili</th>
          <th width="10%"></th>
        </tr>
      </thead>
      <tbody>
        <% items_addable.each do |item| %>
          <% if !orig.has_key_word?(item) && item.leaf? %>
            <tr>
              <td><%= item.get_dinasty %></td>
              <td>
                <%= link_to '', manage_key_word_rels_key_word_path(id: item.id, mode: 0, ot_id: orig.id, ot_cls: orig.class),
                  class: "button radius tiny success foundicon-plus", title: "Aggiungi" %>
              </td>
            </tr>
          <% end %>
        <% end %>
        </tbody>
    </table>
  </div>
</div>

app/views/shared/_lineerror.html.erb
<tr>
  <div class="row">
    <div class="twelve columns offset-by-one">
      <td><%= lineerror.to_s %></td>
    </div>
  </div>
</tr>

app/views/shared/_linesuccess.html.erb
<tr>
  <div class="row">
    <div class="twelve columns offset-by-one">
  	  <td><%= linesuccess.to_s %></td>
    </div>
  </div>
</tr>

app/views/shared/_main_title.html.erb
<div class="row">
  <div class="twelve columns">
    <div class="panel pagetitle">
      <%= t %>
    </div>
    <%= render :partial => 'shared/error_messages', :locals => {:f => record} unless record.nil? %>
  </div>
</div>

app/views/shared/_page_title.html.erb
<h4> <%= @title %> </h4>
<hr />
<%= render :partial => 'shared/error_messages', :locals => {:f => record} unless record.nil? %>

app/views/shared/_topmenu.html.erb
<div class="row">
  <nav class="top-bar">
    <ul>
      <!-- Title Area -->
      <li class="name">
      <h1>
        <%= link_to "G.M.A", root_path %>
      </h1>
      </li>
      <li class="toggle-topbar"><a href="#"></a></li>
    </ul>

    <section>
      <!-- Right Nav Section -->
      <ul class="left">
        <li class="divider"></li>
        <li class="has-dropdown">
          <a href="#" class="foundicon-add-doc">DOCUMENTI</a>
          <ul class="dropdown">
            <% Tesdoc::TIPO_DOC.each do |k, v| %>
              <li> <%= link_to v.upcase, tesdocs_path(:tipo_doc => k) %> </li>
            <% end %>
            <li> <%= link_to "SCADENZE", filter_scadenzas_path %> </li>
          </ul>
        </li>
        <li class="has-dropdown">
          <a href="#" class="foundicon-address-book">
            ANAGRAFICA
          </a>
          <ul class="dropdown">
            <li> <%= link_to "SOGGETTI", anagens_path %> </li>
            <li> <%= link_to "ARTICOLI", articles_path %> </li>
            <li> <%= link_to "CITTA'", localitas_path %> </li>
            <li> <%= link_to "STATI/NAZIONI", paeses_path %> </li>
            <li> <%= link_to "IVA/ESENZIONI", ivas_path %> </li>
            <li> <%= link_to "AGENTI", agentes_path %> </li>
            <li> <%= link_to "EVENTI", events_path() %> </li>
            <li> <%= link_to "CODICI SCONTO", coupons_path(state: 2) %> </li>
            <li> <%= link_to "COUPON GENERICI", coupons_path(state: 1) %> </li>
          </ul>
        </li>
        <li class="has-dropdown">
          <a href="#" class="foundicon-settings">
            CAUSALI
          </a>
          <ul class="dropdown">
            <li> <%= link_to "CONTABILI", causales_path %> </li>
            <li> <%= link_to "DI MAGAZZINO", causmags_path %> </li>
          </ul>
        </li>
        <li class="has-dropdown">
          <a href="#" class="foundicon-edit">
            CONTI
          </a>
          <ul class="dropdown">
            <li> <%= link_to "CLIENTI", contos_path(:tipoconto => 'C') %> </li>
            <li> <%= link_to "FORNITORI", contos_path(:tipoconto => 'F') %> </li>
            <li> <%= link_to "ALTRO", contos_path(:tipoconto => 'A') %> </li>
          </ul>
        </li>
        <li class="has-dropdown">
          <a href="#" class="foundicon-inbox">
            SERVIZI
          </a>
          <ul class="dropdown">
            <li> <%= link_to "CARICA ORDINE(xml)", import_by_xml_tesdocs_path(:tp=>:f1) %> </li>
            <li> <%= link_to "SPED. MASSIVA ABBONAMENTI", import_by_xml_tesdocs_path(:tp=>:f3) %> </li>
            <li> <%= link_to "SPED. SINGOLO ABBONAMENTO", import_by_xml_tesdocs_path(:tp=>:f4) %> </li>
            <li> <%= link_to "CONFIGURAZIONI", confs_path %> </li>
            <li> <%= link_to "KEY_WORDS", key_words_path %> </li>
            <li> <%= link_to "UTENTI", users_path %> </li>
            <li> <%= link_to "ESTRAZIONE UTENTI", export_filter_users_path %> </li>
          </ul>
        </li>
      </ul>
      <ul class="right">
        <li class="divider"></li>
        <li><%= link_to "ESCI", signout_path, :method => :delete, :class=> "foundicon-left-arrow" %></li>
        <li class="divider"></li>
        <li><%= link_to "CAMBIA (#{current_annoese.to_s})", new_session_path(:login => current_user.login), :class=> "foundicon-refresh" %></li>
      </ul>
    </section>
  </nav>
</div>