config/routes.rb
Gma::Application.routes.draw do

  resources :coupons
  resources :anag_socials

  resources :key_words do 
    member do
      get 'manage_key_word_rels'
      get 'change_n_order'
    end
  end

  resources :events

  root :to => "menu#home"

  get "menu/contact"

  get "menu/help"

  match '/signout', :to => 'sessions#destroy'

  resources :sessions, :only => [:new, :create, :destroy]
  
  resources :users do
    collection do
      get :export_filter
      post :do_export_filter
    end
  end

  resources :confs

  resources :localitas do
    collection do
      get :filter
    end
  end

  resources :paeses

  resources :ivas

  resources :causmags

  resources :causales

  resources :agentes

  resources :contos do
    collection do
      get :filter
      get :anagen_exit
    end
  end

  resources :scadenzas do
    collection do
      get :filter
    end
  end

  resources :costos
  resources :spedizs, :only => [:new, :create, :edit, :update, :destroy]  do
    collection do
      get :setind
    end
  end

  resources :articles do
    member do
      get :filter_mov_vend
      get :stp_mov_vend
      get :filter_mov_vend_xls
      get :mov_vend_xls
    end
    collection do
      get :filter
      get :filter_mov_vend_all
      get :stp_mov_vend_all
      get :filter_mov_vend_all_xls
      get :mov_vend_all_xls
      get :set_distrib
    end
  end

  resources :anagens do
    collection do
      get :filter
      get :chg_tipo
      get :change_article
      get :change_event
    end
  end

  resources :anainds do
    collection do
      get :descrizloc
      get :reset_locid
    end
  end

  resources :tesdocs do
    collection do
      get :filter
      get :set_causmags
      get :set_provv
      get :addtesrigdoc_fromxls
      get :genera_xls_articoli
      get :import_by_xml
      post :create_by_xml
      get :form_duplicate
      post :exec_duplicate
    end
    member do
      get :add1row4article
      get :giacyearprec
      get :delrowqta0
      get :stp
      get :dati_ind
      get :stp_ind
      get :ges_datisped
      get :ges_costo
      get :ges_datiscad
      post :addrow_fromxls
      get :upload_xls
    end
  end

  resources :rigdocs do
    collection do
      get :art_cod_exit
      get :art_des_exit
      get :art_sconto_exit
    end
    member do
      get :up
      get :down
    end
  end

	post 'authenticate',  to: 'authentication#authenticate'
  get 'authors',        to: 'anagens#authors'
  get 'teachers',       to: 'anagens#teachers'
  get 'events',         to: 'articles#events'
  get 'categories',     to: 'key_words#categories'
  get 'products',       to: 'articles#products'
  get 'announcements',  to: 'articles#announcements'
  get 'promotions',     to: 'articles#promotions'
  get 'bestsellers',    to: 'articles#bestsellers'
  get 'products',       to: 'articles#products'
  get 'products_query', to: 'articles#products_query'
  get 'anagens_query',  to: 'anagens#anagens_query'
  get 'users_query',    to: 'users#users_query'
  post 'users_query',   to: 'users#users_query'
  get 'get_localitas',  to: 'localitas#localitas_query'
  get 'push_order',     to: 'tesdocs#create_by_json'

  get "api/eshop/v1/get_events",        to: "events#filter_events_ajax"
  get "api/eshop/v1/activate_discount", to: "coupons#activate_discount"











end

app/controllers/anagens_controller.rb
class AnagensController < ApplicationController

  before_filter :authenticate_request, if: :json_request?
  before_filter :authenticate
  before_filter :force_fieldcase, :only => [:create, :update]

  def filter
    @tpfilter  = params[:tpfilter]
    @desfilter = params[:desfilter].strip
    @anagens, nrrecord = Anagen.filter(@tpfilter, @desfilter, params[:page])
    flash_cnt(nrrecord) if params[:page].nil?
    @title = "Elenco Soggetti/Societa'"
    render "index"
  end

  def index
    @title = "Elenco Soggetti/Societa'"
    store_location
    #@anagens = Anagen.paginate(:page => params[:page], :per_page => 10, :order => [:denomin])
  end

  def show
    if params[:id].to_i > 0
      @anagen = Anagen.find(params[:id])
    elsif params[:id].to_i == -1
      @anagen = Anagen.random_author
    end
    @title = "Soggetto/Societa'"
    @art_author = @anagen.anagen_articles.by_author
    @art_print  = @anagen.anagen_articles.by_printer
    @art_own    = @anagen.anagen_articles.by_cd_owner
    #@tesdocs = @anagen.tesdocs.order(data_doc: :desc)
    @bookings = @anagen.prenotazioni
    @subscriptions = @anagen.abbonamenti
    @courses = @anagen.corsi

    @key_words_addable = KeyWord.sort_by_din(KeyWordAnagen.all)
    @articles_addable = Article.libri.order(:descriz)
    @cd_addable = Article.contenuti_digitali.order(:descriz)
    tmp = @anagen.contos.where(tipoconto: "C", annoese: current_annoese).first
    @eshop_orders = tmp ? tmp.tesdocs : []
    @coupons = @anagen.coupons.order("coupons.dt_start DESC")
    @socials = @anagen.anag_socials

    respond_to do |format|
      format.html # renders .html.erb
      #format.json { render :json => { st: true, v: @anagen.to_json } }
      format.json { render json: map_json_result(@anagen) }
    end
  end 

  def new
    @title = "Inserimento Soggetto/Societa'"
    @anagen = Anagen.new
    @anagen.codice = Anagen.newcod
  end

  def edit
    @anagen = Anagen.find(params[:id])
    @title = "Modifica Soggetto/Societa'"
  end

  def chg_tipo
    @anagen = Anagen.new
    @anagen.tipo = params[:anagen][:tipo]
    @anagen.dtnas = '01/01/1980' if @anagen.tipo == 'F' || @anagen.tipo == 'I'
    respond_to do |format|
      format.js
    end
  end

  def create
    @err=0
    respond_to do |format|
      @anagen = Anagen.new(params[:anagen])
      if @anagen.save
        if params[:ins_conto] == 'S'
          @conto = Conto.new
          @conto.azienda = current_user.azienda
          @conto.annoese = current_annoese
          @conto.tipoconto = 'C'
          @conto.codice = Conto.new_codice(@conto.annoese, @conto.azienda, @conto.tipoconto)
          @conto.descriz = @anagen.denomin
          @conto.cntrpartita = nil
          @conto.sconto = 0
          @conto.anagen_id = @anagen.id
          @conto.tipopeo = 'P'
          if @conto.save
            flash[:success] = 'Anagrafica soggetti e conto clienti creati con successo.'
          else
            flash[:error] = 'Anagrafica soggetti creata con successo. (PROBLEMI DURANTE LA CREAZIONE DEL CONTO CLIENTI)'
          end
        else
          flash[:success] = 'Anagrafica soggetti creata con successo.'
        end
      else
        @title = "Nuovo Soggetto/Societa'"
  #      flash.now[:alert] = "Il salvataggio dell'anagrafica non e' andato a buon fine"
        @err=1
      end
      @ins_conto = params[:ins_conto]
      format.js
    end
  end

  def createOLD
    @anagen = Anagen.new(params[:anagen])
    if @anagen.save
      if params[:ins_conto] == 'S'
        @conto = Conto.new
        @conto.azienda = current_user.azienda
        @conto.annoese = current_annoese
        @conto.tipoconto = 'C'
        @conto.codice = Conto.new_codice(@conto.annoese, @conto.azienda, @conto.tipoconto)
        @conto.descriz = @anagen.denomin
        @conto.cntrpartita = nil
        @conto.sconto = 0
        @conto.anagen_id = @anagen.id
        @conto.tipopeo = 'P'
        if @conto.save
          flash[:success] = 'Anagrafica soggetti e conto clienti creati con successo.'
        else
          flash[:error] = 'Anagrafica soggetti creata con successo. (PROBLEMI DURANTE LA CREAZIONE DEL CONTO CLIENTI)'
        end
      else
        flash[:success] = 'Anagrafica soggetti creata con successo.'
      end
      redirect_to @anagen
    else
      @title = "Nuovo Soggetto/Societa'"
#      flash.now[:alert] = "Il salvataggio dell'anagrafica non e' andato a buon fine"
      render :action => "new"
    end
  end

  def update
    @anagen = Anagen.find(params[:id])
    if @anagen.update_attributes(params[:anagen])
      flash[:success] = 'Anagrafica soggetti aggiornata con successo.'
      redirect_to @anagen
    else
      @title = "Modifica Soggetto/Societa'"
#      flash.now[:alert] = "Il salvataggio dell'anagrafica non e' andato a buon fine"
      render :action => "edit"
    end
  end

  def destroy
    @anagen = Anagen.find(params[:id])
    begin
      @anagen.destroy
      flash[:success] = "Cancellazione Eseguita"
    rescue
      flash[:alert] = $!.message
    end
redirect_back_or @anagen
  end

  def change_article
    anagen = Anagen.find(params[:id])
    art_id = params[:article_id] && params[:article_id].to_i
    mode   = params[:mode] && params[:mode].to_i

    if mode == 1 
      st = anagen.connect_article(art_id)
    else 
      st = anagen.remove_article(art_id)
    end
    redirect_to :back, notice: st ? "Operazione completata" : "Operazione fallita"
  end

  def change_event
    anagen   = Anagen.find(params[:id])
    event_id = params[:event_id] && params[:event_id].to_i
    mode     = params[:mode] && params[:mode].to_i
    mode2    = params[:mode2] && params[:mode2].to_i

    if mode == 1 
      st = anagen.connect_event(event_id, mode2)
    else 
      st = anagen.remove_event(event_id, mode2)
    end
    redirect_to :back, notice: st ? "Operazione completata" : "Operazione fallita"
  end

  def authors
    ds = Anagen.authors.select("anagens.id, anagens.denomin, anagens.codnaz")
    render json: ds 
  end

  def teachers
    ds = Anagen.teachers.select("anagens.id, anagens.denomin, anagens.codnaz")
    render json: ds 
  end

  def anagens_query
    ds = Anagen.where(codfis: params[:codice])
    ds = Anagen.where(pariva: params[:codice]) if ds.size == 0
    render json: map_json_array(ds, true)
  end

  private
    def force_fieldcase
      set_fieldcase(:anagen, [:codfis, :pariva, :fax, :telefono], [:email, :web])
    end

    def map_json_array(ds, min=false)
      ris = []
      ds.each do |x|
        ris << map_json_result(x,min)
      end
      ris
    end

    def map_json_result(x, min=false)
      a = min ? [:denomin] : [:bio, :denomin, :codnaz, :id, :codfis, :youtube_presentation]
      h = {}
      a.each { |y| h[y] = x[y] }
      h
    end
end

app/views/anagens/_anag_socials.html.erb
<div class="row">
  <div class="twelve columns button-bar">
    <ul class="button-group">
      <%= link_to 'AGGIUNGI SOCIAL', new_anag_social_path(:anagen_id => @anagen.id), :class => "button radius small new foundicon-add-doc" %>
    </ul>
  </div>
</div>

<table>
  <thead>
    <tr>
      <th>Tipo</th>
      <th>Valore</th>
      <th>Stato</th>
      <th></th>
      <th></th>
    </tr>
  </thead>
  <tbody>
    <% @socials.each do |line| %>
      <tr>
        <td><%= line.dtype %></td>
        <td><%= line.saddr %></td>
        <td><%= line.dstate %></td>
        <td><%= link_to '', edit_anag_social_path(line), :class => "button radius tiny modify foundicon-edit", :title => "Modifica" %></td>
        <td><%= link_to '', line, :confirm => 'Confermi?', :method => :delete, :class => "button radius tiny alert foundicon-trash", :title => "Cancella" %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/anagens/_buttons.html.erb
<div class="row">
  <div class="twelve columns button-bar">
    <ul class="button-group">
      <li>
        <%= link_to 'INDIETRO', resque_location(anagens_path), :class => "button radius small cancel foundicon-left-arrow" %>
      </li>
      <li>
        <%= link_to 'MODIFICA', edit_anagen_path(@anagen), :class => "button radius small modify foundicon-edit" %>
      </li>
      <li>
        <%= link_to 'ELIMINA', @anagen, :confirm => 'Confermi eliminazione?',
                                        :method => :delete, :class => "button radius small alert foundicon-trash" %>
      </li>
    </ul>
    <ul class="button-group">
      <li>
        <%= link_to 'AGGIUNGI INDIRIZZO', new_anaind_path(:id => @anagen.id), :class => "button radius small new foundicon-add-doc" %>
      </li>
    </ul>
  </div>
</div>

app/views/anagens/_coupons.html.erb
<div class="row">
  <div class="twelve columns button-bar">
    <ul class="button-group">
      <%= link_to 'AGGIUNGI COUPON', new_coupon_path(:anagen_id => @anagen.id), :class => "button radius small new foundicon-add-doc" %>
    </ul>
  </div>
</div>

<table>
  <thead>
    <tr>
      <th>Descrizione</th>
      <th>Data inizio</th>
      <th>Data fine</th>
      <th>Valore</th>
      <th>Perc.</th>
      <th>Sped?</th>
      <th>Ordine min</th>
      <th>Stato</th>
      <th>Dato utilizzo</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>
  <tbody>
    <% coupons.each do |line| %>
      <tr>
        <td><%= line.code %></td>
        <td><%= to_date(line.dt_start) %></td>
        <td><%= to_date(line.dt_end) %></td>
        <td><%= to_currency(line.value) %></td>
        <td><%= line.perc || 0.0 %> %</td>
        <td><%= line.d_spediz %></td>
        <td><%= to_currency(line.ord_min) %></td>
        <td><%= line.d_state %></td>
        <td><%= to_date(line.dt_use) %></td>
        <td><%= link_to '', "mailto:#{@anagen.email}?subject=#{line.mail_title}&body=#{line.mail_body}", :class => "button radius tiny foundicon-mail", :title => "Invia mail" %></td>
        <td><%= link_to '', edit_coupon_path(line), :class => "button radius tiny modify foundicon-edit", :title => "Modifica" %></td>
        <td><%= link_to '', line, :confirm => 'Confermi?', :method => :delete, :class => "button radius tiny alert foundicon-trash", :title => "Cancella" %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/anagens/_events.html.erb
<div class="six columns">
  <table>
    <thead>
      <tr>
        <th width="90%">Titolo</th>
        <th width="5%"></th>
        <th width="5%"></th>
      </tr>
    </thead>
    <tbody>
      <% events.each do |event| %>
        <tr>
          <td><%= event.description %></td>
          <td><%= link_to '', event, :class => "button radius tiny view foundicon-page", :title => "Visualizza" %></td>
          <td><%= link_to '', change_event_anagens_path(id: @anagen.id, event_id: event.id, mode: 2), :confirm => 'Confermi?', :class => "button radius tiny alert foundicon-trash", :title => "Cancella" %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/anagens/_filter.html.erb
<fieldset>
  <legend> Ricerca anagrafiche </legend>
  <%= form_tag(:filter_anagens, :method => :get) do %>
  <%= hidden_field_tag :type, params[:type] %>
    <div class="three columns">
      <%= select_tag("tpfilter",
                     options_for_select([["Ragione sociale", "RS"], ["Codice fiscale", "CF"],
                                         ["Partiva iva", "PI"]], @tpfilter)) %>
    </div>
    <div class="five columns">
      <%= text_field_tag "desfilter", @desfilter %>
    </div>
    <div class="four columns">
      <i class="foundicon-search">
        <%= submit_tag 'RICERCA', :class => "button radius small search foundicon-search", :title => "Esegui Ricerca" %>
      </i>
    </div>
  <% end %>
</fieldset>

app/views/anagens/_form.html.erb
<%#= render :partial => 'shared/error_messages', :locals => {:f => @anagen} %>
<%= form_for(@anagen, :remote => (action_name=='new')) do |f| %>
  <%= f.hidden_field :codice %>
  <div class="row">
    <div class="five columns">
      <%= f.label "Codice" %>
      <%= f.number_field :codice, :disabled => true %>
    </div>
    <div class="two columns"></div>
    <div class="five columns">
      <%= f.label :tipo %>
      <%= f.select(:tipo, Anagen::TIPO.invert.sort, { :prompt => true}, 
                 {:data => {:remote => true, :url => url_for(:controller => :anagens,
                                                             :action => :chg_tipo)}}) %>
    </div>
    <div class="twelve columns">
      <%= f.label "Denominazione" %>
      <%= f.text_field :denomin %>
    </div>
    <div class="five columns">
      <%= f.label "Partita Iva" %>
      <%= f.text_field :pariva %>
    </div>
    <div class="two columns"></div>
    <div class="five columns">
      <%= f.label "Codice Fiscale" %>
      <%= f.text_field :codfis %>
    </div>
    <span id="datinas">
      <%= render(:partial => 'datinas') %>
    </span>

    <div class="five columns">
      <%= f.label "Telefono" %>
      <%= f.text_field :telefono %>
    </div>
    <div class="two columns"></div>
    <div class="five columns">
      <%= f.label "Fax" %>
      <%= f.text_field :fax %>
    </div>
    <div class="five columns">
      <%= f.label "Cellulare" %>
      <%= f.text_field :cellulare %>
    </div>
    <div class="two columns"></div>
    <div class="five columns">
      <%= f.label "Codice carta docente" %>
      <%= f.text_field :cod_carta_docente %>
    </div>

    <div class="five columns">
      <%= f.label "E-mail" %>
      <%= f.text_field :email %>
    </div>
    <div class="two columns"></div>
    <div class="five columns">
      <%= f.label "Sito Web" %>
      <%= f.text_field :web %>
    </div>

    <div class="five columns">
      <%= f.label "Codice nazione" %>
      <%= f.text_field :codnaz %>
    </div>
    <div class="two columns"></div>
    <div class="five columns">
      <%= f.label "Codice fatt sdi:" %>
      <%= f.text_field :codident %>
    </div>
    <div class="five columns">
      <%= f.label "PEC" %>
      <%= f.text_field :pec %>
    </div>
    <div class="two columns"></div>
    <div class="five columns">
      <%= f.label "Referente" %>
      <%= f.text_field :referente %>
    </div>

    <div class="five columns">
      <%= f.label "CIG" %>
      <%= f.text_field :cod_cig %>
    </div>
    <div class="two columns"></div>
    <div class="five columns">
      <%= f.label "CUP" %>
      <%= f.text_field :cod_cup %>
    </div>
    <div class="two columns">
      <%= f.label "Split Payement" %>
      <%= f.select(:split_payement, Anagen::SPLIT_PAYEMENTS, { :prompt => true}) %>
    </div>
    <div class="three columns">
      <%= f.label "Codice carta studente" %>
      <%= f.text_field :cod_carta_studente %>
    </div>
    <div class="two columns"></div>
    <div class="five columns">
      <%= f.label "Link presentazione YouTube" %>
      <%= f.text_field :youtube_presentation %>
    </div>

    <% if @anagen.denomin.nil? %>
      <div class="five columns">
        <%= f.label "Inserisci Conto Cliente" %>
        <%= check_box_tag 'ins_conto', 'S', true %>
      </div>
      <div class="two columns"></div>
      <div class="five columns"></div>
    <% end %> 
    <div class="twelve columns">
      <%= f.label "Biografia" %>
      <%= f.text_area :bio %>
    </div>
    <hr />
    <div class="twelve columns">
      <%= f.submit 'SALVA', :class => "button radius small success foundicon-checkmark" %>
      <%= link_to 'ANNULLA', anagens_path(type: params[:type] || @anagen.type), :class => "button radius small alert foundicon-remove" %>
    </div>
  </div>
<% end %>

app/views/anagens/_line.html.erb
<tr>
  <td><%= line.codice %></td>
  <td><%= Anagen::TIPO[line.tipo] %></td>
  <td><%= line.denomin %></td>
  <td><%= line.pi_or_cf %></td>
  <td>
    <%= link_to '', line, :class => "button radius tiny detail foundicon-page", :title => "Dettaglio" %>
  </td>
</tr>

app/views/anagens/_rel_datas.html.erb
<dl class="tabs">
  <dd class="active"><a href="#tesdocs">Documenti</a></dd>
  <dd><a href="#prenots">Prenotazioni</a></dd>
  <dd><a href="#events">Corsi / Eventi</a></dd>
  <dd><a href="#subscrib">Abbonamenti</a></dd>
  <dd><a href="#ordini">Ordini eshop</a></dd>
  <dd><a href="#cdOwn">Contenuti digitali</a></dd>
  <dd><a href="#coupon">Coupons</a></dd>
</dl>

<ul class="tabs-content">
  <li id="tesdocsTab" class="active">
    <%= render partial: "tesdocs", locals: { tesdocs: @tesdocs} %>
  </li>

  <li id="prenotsTab">
    <%= render partial: "events", locals: { events: @bookings} %>
  </li>

  <li id="eventsTab">
    <%= render partial: "events", locals: { events: @courses} %>
  </li>

  <li id="subscribTab">
    <%= render partial: "events", locals: { events: @subscriptions} %>
  </li>

  <li id="ordiniTab">
    <%= render partial: "eshop_orders", locals: { orders: @eshop_orders} %>
  </li>

  <li id="couponTab">
    <%= render partial: "coupons", locals: { coupons: @coupons } %>
  </li>

  <li id="cdOwnTab">
    <%= render partial: "articles", locals: {anagen_articles: @art_own, articles_addable: @cd_addable} %>
  </li>
</ul>

app/views/anagens/chg_tipo.js.erb
  $("#datinas").html("<%= escape_javascript(render(:partial => 'datinas')) %>");

app/views/anagens/create.js.erb
if ("<%=@err%>" == "0")
{
  if ("<%=@ins_conto%>" != "S")
  {
    alert("TOLTO IL CHECK DALL'INSERIMENTO AUTOMATICO DEL CONTO CLIENTE");
  }
  var url = "<%= root_url %>anagens/" + "<%=@anagen.id%>";
}
else
{
  alert("SALVATAGGIO FALLITO");
  var url = "<%= root_url %>anagens/new";  
}

window.location = url;

app/views/anagens/edit.html.erb
<%= render :partial => 'shared/page_title', :locals => {:record => @anagen} %>
<%= render 'form' %>

app/views/anagens/index.html.erb
<%= render :partial => 'shared/page_title', :locals => {:record => nil} %>
<div class="button-bar">
  <ul class="button-group">
    <li>
      <%= link_to 'NUOVA', new_anagen_path(type: params[:type]), :class => "button radius small new foundicon-add-doc" %>
    </li>
  </ul>
</div>
<%= render :partial => 'filter' %>
<% unless @anagens.nil?||@anagens.empty? %>
  <table>
    <thead>
      <tr>
        <th width="6%">Codice</th>
        <th width="10%">Tipo</th>
        <th width="65%">Nominat./Ragione sociale</th>
        <th width="15%">P.I.-C.F.</th>
        <th width="4%"></th>
      </tr>
    </thead>
    <tbody>
        <%= render :partial => 'line', :collection => @anagens %>
    </tbody>
  </table>
  <%= will_paginate @anagens %>
<% end %>

app/views/anagens/show.html.erb
<%= render :partial => 'shared/page_title', :locals => {:record => nil} %>
<%= render partial: "buttons" %>

<hr>

<dl class="tabs">
  <dd class="active"><a href="#gen">Dati anagrafici</a></dd>
  <dd><a href="#addresses">Indirizzi</a></dd>
  <dd><a href="#keywords">Key Word</a></dd>
  <% if @anagen.author? %>
    <dd><a href="#articles">Libri pubblicati</a></dd>
  <% end %>
  <% if @anagen.stampatore? %>
    <dd><a href="#printers">Libri stampati</a></dd>
  <% end %>
  <dd><a href="#socials">Social</a></dd>
</dl>

<ul class="tabs-content">
  <li class="active" id="genTab">
    <%= render partial: "info" %>
  </li>

  <li id="addressesTab">
    <%= render partial: "anainds" %>
  </li>

  <li id="keywordsTab">
    <%= render partial: "shared/key_word_rels", locals: {orig: @anagen, items_addable: @key_words_addable} %>
  </li>

  <li id="articlesTab">
    <%= render partial: "articles", locals: {anagen_articles: @art_author, articles_addable: @articles_addable} %>
  </li>

  <li id="printersTab">
    <%= render partial: "articles", locals: {anagen_articles: @art_print, articles_addable: @articles_addable} %>
  </li>

  <li id="socialsTab">
    <%= render partial: "anag_socials", locals: {socials: @socials} %>
  </li>
</ul>



app/views/anagens/show.json.erb
json.extract! @anagen, :id, :created_at, :updated_at